version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.13.5
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.2
    - 5.28.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
    - 7.13.9
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: spectron
    versions:
    - 13.0.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
